### ISSUE TITLE
Reorganize Index Page

### ISSUE THREAD

**Issue by TrevorDS** [barrycumbie/dev-challenge-01#102]
<h1>Reorganize Index Page</h1>

<h3>Brief</h3>

We need to make the `index.html` more organized. This should include: organization (uniformity). The page should have a set format that all data points follow.

<h3>User Story</h3>

**As a** member of the DEV team (REPO Collaborator)
**I want** to reorganize the ```index.html```
**so that** the user would see our new, organized `index.hml`, and be able to more easily navigate and digest what our webpage is trying to convey.

<h3>Dev Points (User Story Points)</h3>

+1-2 point(s) - depends on how much you organize. 🤠 

<h3>Resources</h3>

<ol>
<li>HTML</li>
<li>Git BASH / Pull Request</li>
<li>Other Collaborator's inputs</li>
</ol>

<h3>Approach</h3>

We should:

<ol>
<li>Make the page have a defined "format" for how the data is organized.</li>
<li>Make all the links in a uniformed format.</li>
<li>Keep everything uniform and succinct.</li>
</ol>

**Comment by barrycumbie** [comment]
@TrevorDS where my *user story* & *story points*?

Also: TOO BIG in SCOPE! Issue needs to be narrow. Just one of these...re-org one part, add style, ... just one thing!

**Comment by TrevorDS** [comment]
Sounds good. I updated my Issue Card to properly define my proposed issue.

**Comment by barrycumbie** [comment]
😕 (confused) on User Story: Starts out ** As a dev ** but pivots ** so that ** the user. 

What if: As a DEV, I want to all the DEV-CHALLENGE instructions easy to find...

As a NEW USER, I want to visit the index.html and KNOW what this page is supposed to be...

As an EMPLOYER/ALUM, I want to browse profiles of DEVS...

(Notice ☝🏼 three different issues...try to narrow your scope. Re-org is too broad. Look at #108 and #104 and my comments...see how specific they get: delete this file, rename this file. Can yours be this specific: create a <section> on index.html to contain dev profile links)
