### ISSUE TITLE
Delete joshua-dev-profile

### ISSUE THREAD

**Issue by JMitch55** [barrycumbie/dev-challenge-01#104]
- **Difficulty:** 1 point

- **User story**: As a collaborator, I want to delete joshua-dev-profile, so that the repo can be cleaned up as well as eliminate duplicate files. 

- **Background info**: I have went ahead today and pushed my file into the dev-profile folder. So, there should be no need for that other file that is just floating around.

- **Approach**: As collaborators on the repo we should have the ability to delete the file, I believe this would take the same approach as adding a file, that being going into the CLI, cloning the repo, deleting, committing, pushing, etc.

- **Resources**: [https://github.com/barrycumbie/dev-challenge-01](url)

**Comment by barrycumbie** [comment]
okay, very close. Try the user story again. 

* As a ___, I want ____, so that _____. *

**Comment by barrycumbie** [comment]
I'll accept the user story....you did follow my example but i/c readability by:

*As a* ___
*I want* ___
*So that* ___

☝🏼 ya know, each on its own line.

## But I do need to know more about this:

> I want to delete joshua-dev-profile

tell us where this lives in the file directory? Look at #108 about how to depict the directory structure in a comment and that way you can EXPLICTALLY tell us the full path of the file to be deleted and the full path of the file to be kept. 

Hey, by the end of this issue (here or the related PR) you could even give us the exact CLI used:

```shell
# of course...create a branch first and do this on the branch, not on the main

# navidate to repo root/
rm -r docs/joshua-dev-profile # recursively removed the duplicate file
# now tell git about the changes
git status # should show that file in red
git rm docs/joshua-dev-profile
git status # should show that file in green
git commit -m 'removed 2x file'
git push
# git will yell at you about setting the upstream, copy their suggestion and use that
```

**Comment by barrycumbie** [comment]
Forgot this! I might have accepted this issue too soon...missing a 

# TEST 

1. Navigate to the REPO Source Code: https://github.com/barrycumbie/dev-challenge-01
2. Scan all files/folders, identifying files named exactly or close to: ```joshua-dev-profile```
3. List all possible duplicate files 
4. Affirm that each listed file is unique and necessary and that one file exists and is in the ```dev-profile/```

(hey this is almost starting to look like an algorithm)
