### ISSUE TITLE
Fixing issue #98 - dev03 gitcommands page

### ISSUE THREAD

**Issue by bendavis91** [barrycumbie/dev-challenge-01#108]
## __User Story__ 
__As a__ DEV
__I want__ to point out a few issues with a Dev03 #98 merge pertaining to an incorrect file name and extension for gitbranch-iss98 in the course-content folder, and dev-03-gitcommands in the docs folder that should be in the course-content folder
__so that__ we as a team can work towards a cleaner working environment for our product.

* __gitbranch-iss98__ in the __course-content__ folder looks like it was intended to be named __dev-03-gitcommands__, and also it is missing a __.html file type__. So rename that file and add the proper file type for the web page to work.
* __dev-03-gitcommands__ in the docs folder was placed outside of the course-content folder, so that needs to be __removed__.

```
.
├── course-content
│   ├── cli-commands.html
│   ├── course-info.html
│   ├── gitbranch-iss98
│   ├── markdownSyntax.html
│   ├── pull-request-advice.html
│   └── temp.txt
├── dev-03-gitcommands
├── dev-instructions
│   └── dev-03-instructions.md
├── dev-profile
│   ├── Estacio-dev-profile.html
│   ├── alsup-dev-profile.html
│   ├── codys-dev-profile.html
│   ├── davis-dev-profile.html
│   ├── escobar-dev-profile.html
│   ├── hammond-dev-profile.html
│   ├── humphreys-dev-profile.html
│   ├── joe_dev.html
│   ├── josh-dev-challenge.html
│   ├── joshua-dev-profile.html
│   ├── luan-dev-profile.html
│   ├── owen-dev-profile.html
│   ├── reid-dev-profile.html
│   ├── sevigne-dev-profile.html
│   └── sherrill.html
├── dont-do-this.html
├── index.html
├── joshua-dev-profile.html
├── lib
│   ├── img
│   │   └── TrevorDS
│   │       └── tds_examplePR.png
│   ├── scripts
│   └── styles
└── noah-dev-profile
    └── noah-dev-profile.html
```
## __Approach__ 
After reviewing our repo I noticed a few issues that needed to be cleaned up. As a collaborator we should look to fixing the repository to be properly formatted and clean.
## __Test:__ 
Edit and test the files locally before adding them into the repository.
1. Navigate through the repo and find the files to be edited.
2. On your local repo do a git update/pull
3. Show a list of all files (on windows) ```$ tree.com //a //f``` or any preferred tree command to check for any files without a period ```.``` 
4. Determine if any of those files should be changed(some files may not need a ```.``` if its a special file).
5. Examine the file contents inside the tree to check for proper file names
6. If any files are in an improper name format use ```$ git mv old_filename new_filename``` to change file names
7. To delete a file use ```$ git rm filename``` 
7. Search the site for any files linking to the edited file (run the test site through a [site map generate](https://www.xml-sitemaps.com/) / [broken link validator](https://validator.w3.org/checklink))
(just making sure your changes didn't break any link/dependences)

## __Difficulty:__ 
2 point

**Comment by barrycumbie** [comment]
Good start @bendavis91 

Try the user story again & stick to the *as a ___, I want ____, so that _____. *

List the specific misnamed files and everything. Hell, even try this:

+ docs/
|
|
|

hold on...there's an easier way to do this. I'll workin on it: https://www.cyberciti.biz/faq/linux-show-directory-structure-command-line/

**Comment by barrycumbie** [comment]
got it!

```
.
├── course-content
│   ├── cli-commands.html
│   ├── course-info.html
│   ├── gitbranch-iss98
│   ├── markdownSyntax.html
│   ├── pull-request-advice.html
│   └── temp.txt
├── dev-03-gitcommands
├── dev-instructions
│   └── dev-03-instructions.md
├── dev-profile
│   ├── Estacio-dev-profile.html
│   ├── alsup-dev-profile.html
│   ├── codys-dev-profile.html
│   ├── davis-dev-profile.html
│   ├── escobar-dev-profile.html
│   ├── hammond-dev-profile.html
│   ├── humphreys-dev-profile.html
│   ├── joe_dev.html
│   ├── josh-dev-challenge.html
│   ├── joshua-dev-profile.html
│   ├── luan-dev-profile.html
│   ├── owen-dev-profile.html
│   ├── reid-dev-profile.html
│   ├── sevigne-dev-profile.html
│   └── sherrill.html
├── dont-do-this.html
├── index.html
├── joshua-dev-profile.html
├── lib
│   ├── img
│   │   └── TrevorDS
│   │       └── tds_examplePR.png
│   ├── scripts
│   └── styles
└── noah-dev-profile
    └── noah-dev-profile.html
```

**Comment by barrycumbie** [comment]
tell us which files exactly to move/rename/edit fix!

**Comment by bendavis91** [comment]
@barrycumbie Edited original comment above.

**Comment by barrycumbie** [comment]
Okay, I'll accept it with these recommendations:

## use code markdown 

The file tree you gave us in your comment...use the the code syntax markdown, which are three of these: ` (👈🏼 that lil symbol just to the left of 1 on your keyboard) 

So, this, like you have it: 

├── course-content
│ ├── cli-commands.html
│ ├── course-info.html
│ ├── gitbranch-iss98
│ ├── markdownSyntax.html

becomes this

```
├── course-content
│ ├── cli-commands.html
│ ├── course-info.html
│ ├── gitbranch-iss98
│ ├── markdownSyntax.html
```

## a tweak to your user story too

>As a team member of the dev team
>I want to point out a few issues with a Dev03 #98 merge including misplaced files in the wrong folder, misnamed files, and an incorrect file extension
>so that we as a team can work towards a cleaner working environment for our product.

Try 

*As a* DEV (or USER) 
*I want* valid file names, extensions & logically grouped files
*So that* (I like what you said :point_up)

**Comment by barrycumbie** [comment]
hey @bendavis91 check on iss #108...it may take care of one file in the scope of this issue. 

Also: bump your story points up to 2 since this has more moving parts. 

In the future, consider making your issues singluar, each of these could be their own issue:
- move stray dev-profiles ```.html``` into the ```dev-profile/``` dir
- delete test and junk files: ```then list the specific ones```
- add file extensions to these files: ``` whatever ```

see, each could be own issue, at 1 point a pop

**Comment by barrycumbie** [comment]
test needs some work 

>## TEST 
>Edit and test the files locally before adding them into the repository.

See my comments to #104 that looks more like a test, yours might be: 

1. on your git clone, update/pull
2. nav to docs/
3. run some command to list out all files/folders (```tree -c``` for example, if you have it installed, probably a ```grep``` comand)
4. identify all files (not folders/) without a period ```.``` 
5. if any exist, assess if they are okay like (some special file), otherwise mark for file name needed
6. examine file contents to determine proper file name
... can cut off here, but could keep going 
7. search the site for any files linking to the edited file (run the test site through a site map generate/broken link validator)
(just making sure your changes didn't break any link/dependeinces

See why it is good to not make compound or complex issues...ultimately we are getting at writing tests that can be automated with a script.

**Comment by bendavis91** [comment]
@barrycumbie :thumbsup:

**Comment by olivia7n** [comment]
After looking through this issue as a code reviewer, the test was easy to follow but initially included too much information in each step.
