### ISSUE TITLE
Delete temp.txt file in course-content/

### ISSUE THREAD

**Issue by williamoyen** [barrycumbie/dev-challenge-01#152]
### User Story: 
**As a** collaborator on the repo
**I want** to delete the ```temp.txt``` file in ```course-content ```
**So that** it is removed from the directory since it is a blank file that was created to add the ```course-content``` directory to the repo.

### Process:
1. Make sure my local dev environment is up to date with the remote GitHub repo
2. Create a branch called iss152
3.  Navigate to the ```course-content``` directory
4. Run commands to remove ```temp.txt```

### Commands :
```git pull```  #Makes sure your local dev environment is up to date
```git checkout -b iss152``` #Create the branch for the issue and checkout that branch
``` rm -r temp.txt``` #Delete the file
```git rm temp.txt``` #Remove the file

### Test:
To test whether the file was removed you can navigate to the ```course-content``` directory in the repo and see if the file is there.
Another way to test is to try and navigate to [https://barrycumbie.github.io/dev-challenge-01/course-content/temp.txt](https://barrycumbie.github.io/dev-challenge-01/course-content/temp.txt), if the file is removed this should result in a 404 error.

**Comment by barrycumbie** [comment]
Good issue card content overall. Just spice it up some with MD syntax. 

- Use ```# and ##``` for section headers 
- Surround text with three of these ` for code syntax and file/dir names ```course-content``` and git commands
- break user story into lines with bold with double splats (*) 

**As a** _____
**I want** _____
**So that** ______

How do we make sure local DEVBOX is up to date? 
How do we create the iss# (cmds?) and now you know the exact branch name right? #152
Also, before you run the ```git rm filename``` you should first delete the file ```rm -r filename```

**Comment by williamoyen** [comment]
@barrycumbie I updated the issue card and it looks a lot better now 👍
